---
name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Lint the code
        run: yarn lint
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: yorangyselenhogent/webapp:latest